-- MySQL Script generated by MySQL Workbench
-- Tue Jul  2 20:41:30 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CondicionEspecial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CondicionEspecial` (
  `idCondicionEspecial` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCondicionEspecial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `idPersona` INT NOT NULL,
  `pnombre` VARCHAR(45) NOT NULL,
  `snombre` VARCHAR(45) NULL,
  `papellido` VARCHAR(45) NOT NULL,
  `sapellido` VARCHAR(45) NULL,
  `identidad` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `genero` VARCHAR(45) NULL,
  `direccion` VARCHAR(200) NULL,
  `idCondicionEspecial` INT NOT NULL,
  PRIMARY KEY (`idPersona`),
  INDEX `fk_Persona_CondicionEspecial1_idx` (`idCondicionEspecial` ASC) VISIBLE,
  CONSTRAINT `fk_Persona_CondicionEspecial1`
    FOREIGN KEY (`idCondicionEspecial`)
    REFERENCES `mydb`.`CondicionEspecial` (`idCondicionEspecial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Telefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Telefono` (
  `idTelefono` INT NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `tipoTelefono` VARCHAR(45) NULL COMMENT 'El numero de telefono puede ser:\n-Empresarial: Tigo o Claro\n-Casa\n-Trabajo\n-Personal',
  `idPersona` INT NOT NULL,
  PRIMARY KEY (`idTelefono`),
  INDEX `fk_Telefono_Persona_idx` (`idPersona` ASC) VISIBLE,
  CONSTRAINT `fk_Telefono_Persona`
    FOREIGN KEY (`idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoCliente` (
  `idTipoCliente` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL COMMENT '-Normal\n-especial\n-etc...',
  PRIMARY KEY (`idTipoCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `fechaRegistro` DATE NOT NULL,
  `idPersona` INT NOT NULL,
  `idTipoCliente` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_Cliente_Persona1_idx` (`idPersona` ASC) VISIBLE,
  INDEX `fk_Cliente_TipoCliente1_idx` (`idTipoCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_TipoCliente1`
    FOREIGN KEY (`idTipoCliente`)
    REFERENCES `mydb`.`TipoCliente` (`idTipoCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoEmpleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoEmpleado` (
  `idTipoEmpleado` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL COMMENT '-Gerente\n-Farmaceutico\n-Conserje\n-etc...',
  PRIMARY KEY (`idTipoEmpleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sucursal` (
  `idSucursal` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(1000) NOT NULL,
  `telefono` VARCHAR(100) NULL,
  `idEmpleadoEncargado` INT NULL,
  PRIMARY KEY (`idSucursal`),
  INDEX `fk_Sucursal_Empleado1_idx` (`idEmpleadoEncargado` ASC) VISIBLE,
  CONSTRAINT `fk_Sucursal_Empleado1`
    FOREIGN KEY (`idEmpleadoEncargado`)
    REFERENCES `mydb`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `idEmpleado` INT NOT NULL,
  `fechaRegistro` DATE NOT NULL,
  `idPersona` INT NOT NULL,
  `idTipoEmpleado` INT NOT NULL,
  `idSucursal` INT NULL,
  `usuario` VARCHAR(45) NULL,
  `contrasenia` VARCHAR(45) NULL,
  `direccionImagen` VARCHAR(10000) NULL,
  `Empleadocol` VARCHAR(45) NULL,
  PRIMARY KEY (`idEmpleado`),
  INDEX `fk_Empleado_Persona1_idx` (`idPersona` ASC) VISIBLE,
  INDEX `fk_Empleado_TipoEmpleado1_idx` (`idTipoEmpleado` ASC) VISIBLE,
  INDEX `fk_Empleado_Sucursal1_idx` (`idSucursal` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_TipoEmpleado1`
    FOREIGN KEY (`idTipoEmpleado`)
    REFERENCES `mydb`.`TipoEmpleado` (`idTipoEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_Sucursal1`
    FOREIGN KEY (`idSucursal`)
    REFERENCES `mydb`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoTarjeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoTarjeta` (
  `idTipoTarjeta` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `fechaEmision` DATE NOT NULL,
  `fechaVencimiento` DATE NULL,
  PRIMARY KEY (`idTipoTarjeta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TarjetaAcumulacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TarjetaAcumulacion` (
  `idTarjetaAcumulacion` INT NOT NULL,
  `fechaEmision` DATE NULL,
  `fechaVencimiento` DATE NULL,
  `idTipoTarjeta` INT NOT NULL,
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`idTarjetaAcumulacion`),
  INDEX `fk_TarjetaAcumulacion_TipoTarjeta1_idx` (`idTipoTarjeta` ASC) VISIBLE,
  INDEX `fk_TarjetaAcumulacion_Cliente1_idx` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_TarjetaAcumulacion_TipoTarjeta1`
    FOREIGN KEY (`idTipoTarjeta`)
    REFERENCES `mydb`.`TipoTarjeta` (`idTipoTarjeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TarjetaAcumulacion_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoMovimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoMovimiento` (
  `idTipoMovimiento` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoMovimiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Impuesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Impuesto` (
  `idImpuesto` INT NOT NULL,
  `impuesto` FLOAT NOT NULL COMMENT 'Porcentaje del impuesto establecido.',
  `fechaVigencia` DATE NULL,
  `fechaExpiracion` DATE NULL,
  PRIMARY KEY (`idImpuesto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Factura` (
  `idFactura` INT NOT NULL,
  `fechaHora` DATETIME NOT NULL,
  `subTotal` FLOAT NULL,
  `descuento` FLOAT NULL,
  `impuesto` FLOAT NULL,
  `Total` FLOAT NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  `idCliente` INT NULL,
  `idImpuesto` INT NOT NULL,
  `RTN` VARCHAR(45) NULL,
  `idEmpleado` INT NOT NULL,
  PRIMARY KEY (`idFactura`),
  INDEX `fk_Factura_Cliente1_idx` (`idCliente` ASC) VISIBLE,
  INDEX `fk_Factura_Impuesto1_idx` (`idImpuesto` ASC) VISIBLE,
  INDEX `fk_Factura_Empleado1_idx` (`idEmpleado` ASC) VISIBLE,
  CONSTRAINT `fk_Factura_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Impuesto1`
    FOREIGN KEY (`idImpuesto`)
    REFERENCES `mydb`.`Impuesto` (`idImpuesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Empleado1`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `mydb`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Movimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Movimientos` (
  `idMovimientos` INT NOT NULL,
  `fechaHora` DATETIME NULL,
  `cantidadPuntos` INT NULL,
  `idTarjetaAcumulacion` INT NOT NULL,
  `idTipoMovimiento` INT NOT NULL,
  `idEmpleado` INT NOT NULL,
  `idFactura` INT NOT NULL,
  PRIMARY KEY (`idMovimientos`),
  INDEX `fk_Movimientos_TarjetaAcumulacion1_idx` (`idTarjetaAcumulacion` ASC) VISIBLE,
  INDEX `fk_Movimientos_TipoMovimiento1_idx` (`idTipoMovimiento` ASC) VISIBLE,
  INDEX `fk_Movimientos_Empleado1_idx` (`idEmpleado` ASC) VISIBLE,
  INDEX `fk_Movimientos_Factura1_idx` (`idFactura` ASC) VISIBLE,
  CONSTRAINT `fk_Movimientos_TarjetaAcumulacion1`
    FOREIGN KEY (`idTarjetaAcumulacion`)
    REFERENCES `mydb`.`TarjetaAcumulacion` (`idTarjetaAcumulacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movimientos_TipoMovimiento1`
    FOREIGN KEY (`idTipoMovimiento`)
    REFERENCES `mydb`.`TipoMovimiento` (`idTipoMovimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movimientos_Empleado1`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `mydb`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movimientos_Factura1`
    FOREIGN KEY (`idFactura`)
    REFERENCES `mydb`.`Factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoDescuento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoDescuento` (
  `idTipoDescuento` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoDescuento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Descuento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Descuento` (
  `idDescuento` INT NOT NULL,
  `descuento` FLOAT NOT NULL COMMENT 'Porcentaje del descuento que se va a dar.',
  `idTipoDescuento` INT NOT NULL,
  `fechaEmision` DATE NULL,
  `fechaExpiro` DATE NULL,
  PRIMARY KEY (`idDescuento`),
  INDEX `fk_Descuento_TipoDescuento1_idx` (`idTipoDescuento` ASC) VISIBLE,
  CONSTRAINT `fk_Descuento_TipoDescuento1`
    FOREIGN KEY (`idTipoDescuento`)
    REFERENCES `mydb`.`TipoDescuento` (`idTipoDescuento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FormaPago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FormaPago` (
  `idFormaPago` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idFormaPago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Factura_has_FormaPago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Factura_has_FormaPago` (
  `idFactura` INT NOT NULL,
  `idFormaPago` INT NOT NULL,
  `cantidadPago` FLOAT NULL,
  PRIMARY KEY (`idFactura`, `idFormaPago`),
  INDEX `fk_Factura_has_FormaPago_FormaPago1_idx` (`idFormaPago` ASC) VISIBLE,
  INDEX `fk_Factura_has_FormaPago_Factura1_idx` (`idFactura` ASC) VISIBLE,
  CONSTRAINT `fk_Factura_has_FormaPago_Factura1`
    FOREIGN KEY (`idFactura`)
    REFERENCES `mydb`.`Factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_has_FormaPago_FormaPago1`
    FOREIGN KEY (`idFormaPago`)
    REFERENCES `mydb`.`FormaPago` (`idFormaPago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Descuento_has_Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Descuento_has_Factura` (
  `idDescuento` INT NOT NULL,
  `idFactura` INT NOT NULL,
  PRIMARY KEY (`idDescuento`, `idFactura`),
  INDEX `fk_Descuento_has_Factura_Factura1_idx` (`idFactura` ASC) VISIBLE,
  INDEX `fk_Descuento_has_Factura_Descuento1_idx` (`idDescuento` ASC) VISIBLE,
  CONSTRAINT `fk_Descuento_has_Factura_Descuento1`
    FOREIGN KEY (`idDescuento`)
    REFERENCES `mydb`.`Descuento` (`idDescuento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Descuento_has_Factura_Factura1`
    FOREIGN KEY (`idFactura`)
    REFERENCES `mydb`.`Factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inventario` (
  `idInventario` INT NOT NULL,
  `idSucursal` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idInventario`),
  INDEX `fk_Inventario_Sucursal1_idx` (`idSucursal` ASC) VISIBLE,
  CONSTRAINT `fk_Inventario_Sucursal1`
    FOREIGN KEY (`idSucursal`)
    REFERENCES `mydb`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `idProducto` INT NOT NULL,
  `nombreProducto` VARCHAR(45) NOT NULL,
  `fechaElaboracion` DATE NOT NULL,
  `fechaVencimiento` DATE NOT NULL,
  `serie` VARCHAR(45) NULL,
  `lote` VARCHAR(45) NULL,
  `precioVenta` FLOAT NOT NULL,
  `precioCosto` FLOAT NOT NULL,
  `direccionImagen` VARCHAR(10000) NULL,
  `idInventario` INT NOT NULL,
  `fechaRegistro` DATE NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_Producto_Inventario1_idx` (`idInventario` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_Inventario1`
    FOREIGN KEY (`idInventario`)
    REFERENCES `mydb`.`Inventario` (`idInventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Factura_has_Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Factura_has_Producto` (
  `Factura_idFactura` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  `cantidadCaja` INT NULL,
  `cantidadBlister` INT NULL,
  `cantidadUnidad` INT NULL,
  PRIMARY KEY (`Factura_idFactura`, `Producto_idProducto`),
  INDEX `fk_Factura_has_Producto_Producto1_idx` (`Producto_idProducto` ASC) VISIBLE,
  INDEX `fk_Factura_has_Producto_Factura1_idx` (`Factura_idFactura` ASC) VISIBLE,
  CONSTRAINT `fk_Factura_has_Producto_Factura1`
    FOREIGN KEY (`Factura_idFactura`)
    REFERENCES `mydb`.`Factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_has_Producto_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProductosVarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProductosVarios` (
  `idProductosVarios` INT NOT NULL,
  `idProducto` INT NOT NULL,
  PRIMARY KEY (`idProductosVarios`),
  INDEX `fk_ProductosVarios_Producto1_idx` (`idProducto` ASC) VISIBLE,
  CONSTRAINT `fk_ProductosVarios_Producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medicamento` (
  `idMedicamento` INT NOT NULL,
  `indicacion` VARCHAR(1000) NULL,
  `elaboracion` VARCHAR(1000) NULL COMMENT 'Campo para describir con que materiales/quimicos fue hecho el producto.',
  `idProducto` INT NOT NULL,
  PRIMARY KEY (`idMedicamento`),
  INDEX `fk_Medicamento_Producto1_idx` (`idProducto` ASC) VISIBLE,
  CONSTRAINT `fk_Medicamento_Producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proveedor` (
  `idProveedor` INT NOT NULL,
  `nombre` VARCHAR(100) NULL,
  `RTN` VARCHAR(45) NULL,
  `fechaRegistro` DATE NULL,
  `direccion` VARCHAR(1000) NULL,
  `telefono` VARCHAR(100) NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proveedor_has_Medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proveedor_has_Medicamento` (
  `Proveedor_idProveedor` INT NOT NULL,
  `Medicamento_idMedicamento` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `fechaIngreso` DATE NULL,
  PRIMARY KEY (`Proveedor_idProveedor`, `Medicamento_idMedicamento`),
  INDEX `fk_Proveedor_has_Medicamento_Medicamento1_idx` (`Medicamento_idMedicamento` ASC) VISIBLE,
  INDEX `fk_Proveedor_has_Medicamento_Proveedor1_idx` (`Proveedor_idProveedor` ASC) VISIBLE,
  CONSTRAINT `fk_Proveedor_has_Medicamento_Proveedor1`
    FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `mydb`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proveedor_has_Medicamento_Medicamento1`
    FOREIGN KEY (`Medicamento_idMedicamento`)
    REFERENCES `mydb`.`Medicamento` (`idMedicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Salida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Salida` (
  `idSalida` INT NOT NULL,
  `fechaHora` DATETIME NOT NULL,
  `observacion` VARCHAR(3000) NULL,
  `idSucursalLlegada` INT NOT NULL,
  PRIMARY KEY (`idSalida`),
  INDEX `fk_Salida_Sucursal1_idx` (`idSucursalLlegada` ASC) VISIBLE,
  CONSTRAINT `fk_Salida_Sucursal1`
    FOREIGN KEY (`idSucursalLlegada`)
    REFERENCES `mydb`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medicamento_has_Salida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medicamento_has_Salida` (
  `idMedicamento` INT NOT NULL,
  `idSalida` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`idMedicamento`, `idSalida`),
  INDEX `fk_Medicamento_has_Salida_Salida1_idx` (`idSalida` ASC) VISIBLE,
  INDEX `fk_Medicamento_has_Salida_Medicamento1_idx` (`idMedicamento` ASC) VISIBLE,
  CONSTRAINT `fk_Medicamento_has_Salida_Medicamento1`
    FOREIGN KEY (`idMedicamento`)
    REFERENCES `mydb`.`Medicamento` (`idMedicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medicamento_has_Salida_Salida1`
    FOREIGN KEY (`idSalida`)
    REFERENCES `mydb`.`Salida` (`idSalida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cubiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cubiculo` (
  `idcubiculo` INT NOT NULL,
  `nombreCubiculo` VARCHAR(45) NULL,
  PRIMARY KEY (`idcubiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto_has_cubiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto_has_cubiculo` (
  `Producto_idProducto` INT NOT NULL,
  `cubiculo_idcubiculo` INT NOT NULL,
  PRIMARY KEY (`Producto_idProducto`, `cubiculo_idcubiculo`),
  INDEX `fk_Producto_has_cubiculo_cubiculo1_idx` (`cubiculo_idcubiculo` ASC) VISIBLE,
  INDEX `fk_Producto_has_cubiculo_Producto1_idx` (`Producto_idProducto` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_has_cubiculo_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_cubiculo_cubiculo1`
    FOREIGN KEY (`cubiculo_idcubiculo`)
    REFERENCES `mydb`.`cubiculo` (`idcubiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estante` (
  `idEstante` INT NOT NULL,
  `numeroEstante` VARCHAR(45) NULL,
  `cubiculo_idcubiculo` INT NOT NULL,
  `Sucursal_idSucursal` INT NOT NULL,
  PRIMARY KEY (`idEstante`),
  INDEX `fk_Estante_cubiculo1_idx` (`cubiculo_idcubiculo` ASC) VISIBLE,
  INDEX `fk_Estante_Sucursal1_idx` (`Sucursal_idSucursal` ASC) VISIBLE,
  CONSTRAINT `fk_Estante_cubiculo1`
    FOREIGN KEY (`cubiculo_idcubiculo`)
    REFERENCES `mydb`.`cubiculo` (`idcubiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estante_Sucursal1`
    FOREIGN KEY (`Sucursal_idSucursal`)
    REFERENCES `mydb`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cantidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cantidad` (
  `idCantidad` INT NOT NULL,
  `cantidadCaja` INT NULL,
  `precioVentaCaja` FLOAT NULL,
  `cantidadBlister` INT NULL,
  `precioVentaBlister` FLOAT NULL,
  `cantidadUnidad` INT NULL,
  `precioVentaUnidad` FLOAT NULL,
  `idProducto` INT NOT NULL,
  PRIMARY KEY (`idCantidad`),
  INDEX `fk_Cantidad_Producto1_idx` (`idProducto` ASC) VISIBLE,
  CONSTRAINT `fk_Cantidad_Producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CantidadEntrante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CantidadEntrante` (
  `idCantidad` INT NOT NULL,
  `cantidadCaja` INT NULL,
  `precioCostoCaja` FLOAT NULL,
  `cantidaBlister` INT NULL,
  `precioCostoBlister` FLOAT NULL,
  `cantidadUnidad` INT NULL,
  `precioCostoUnidad` FLOAT NULL,
  `idProveedor` INT NOT NULL,
  `idMedicamento` INT NOT NULL,
  PRIMARY KEY (`idCantidad`),
  INDEX `fk_CantidadEntrante_Proveedor_has_Medicamento1_idx` (`idProveedor` ASC, `idMedicamento` ASC) VISIBLE,
  CONSTRAINT `fk_CantidadEntrante_Proveedor_has_Medicamento1`
    FOREIGN KEY (`idProveedor` , `idMedicamento`)
    REFERENCES `mydb`.`Proveedor_has_Medicamento` (`Proveedor_idProveedor` , `Medicamento_idMedicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto_has_Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto_has_Categoria` (
  `Producto_idProducto` INT NOT NULL,
  `Categoria_idCategoria` INT NOT NULL,
  PRIMARY KEY (`Producto_idProducto`, `Categoria_idCategoria`),
  INDEX `fk_Producto_has_Categoria_Categoria1_idx` (`Categoria_idCategoria` ASC) VISIBLE,
  INDEX `fk_Producto_has_Categoria_Producto1_idx` (`Producto_idProducto` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_has_Categoria_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_Categoria_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `mydb`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
