-- MySQL Script generated by MySQL Workbench
-- Tue Jul 16 10:05:32 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbfarmacia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbfarmacia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbfarmacia` DEFAULT CHARACTER SET utf8 ;
USE `dbfarmacia` ;

-- -----------------------------------------------------
-- Table `dbfarmacia`.`CondicionEspecial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfarmacia`.`CondicionEspecial` (
  `idCondicionEspecial` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCondicionEspecial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfarmacia`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfarmacia`.`Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `pnombre` VARCHAR(45) NOT NULL,
  `snombre` VARCHAR(45) NULL,
  `papellido` VARCHAR(45) NOT NULL,
  `sapellido` VARCHAR(45) NULL,
  `identidad` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `genero` VARCHAR(45) NULL,
  `direccion` VARCHAR(2000) NULL,
  `idCondicionEspecial` INT NOT NULL,
  `estadoPersona` VARCHAR(1) NULL COMMENT 'Campo para eliminar una persona:\nD - Delete\nA - Activo',
  PRIMARY KEY (`idPersona`),
  CONSTRAINT `fk_Persona_CondicionEspecial1`
    FOREIGN KEY (`idCondicionEspecial`)
    REFERENCES `dbfarmacia`.`CondicionEspecial` (`idCondicionEspecial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfarmacia`.`Telefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfarmacia`.`Telefono` (
  `idTelefono` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NOT NULL,
  `tipoTelefono` VARCHAR(45) NULL COMMENT 'El numero de telefono puede ser:\n-Empresarial: Tigo o Claro\n-Casa\n-Trabajo\n-Personal',
  `idPersona` INT NOT NULL,
  PRIMARY KEY (`idTelefono`),
  CONSTRAINT `fk_Telefono_Persona`
    FOREIGN KEY (`idPersona`)
    REFERENCES `dbfarmacia`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfarmacia`.`TipoCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfarmacia`.`TipoCliente` (
  `idTipoCliente` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL COMMENT '-Normal\n-especial\n-etc...',
  PRIMARY KEY (`idTipoCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfarmacia`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfarmacia`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `fechaRegistro` DATE NOT NULL,
  `idPersona` INT NOT NULL,
  `idTipoCliente` INT NOT NULL,
  `estadoCliente` VARCHAR(1) NULL,
  PRIMARY KEY (`idCliente`),
  CONSTRAINT `fk_Cliente_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `dbfarmacia`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_TipoCliente1`
    FOREIGN KEY (`idTipoCliente`)
    REFERENCES `dbfarmacia`.`TipoCliente` (`idTipoCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfarmacia`.`TipoEmpleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfarmacia`.`TipoEmpleado` (
  `idTipoEmpleado` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL COMMENT '-Gerente\n-Farmaceutico\n-Conserje\n-etc...',
  PRIMARY KEY (`idTipoEmpleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfarmacia`.`Sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfarmacia`.`Sucursal` (
  `idSucursal` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(1000) NOT NULL,
  `telefono` VARCHAR(100) NULL,
  `estadoSucursal` VARCHAR(1) NULL,
  PRIMARY KEY (`idSucursal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfarmacia`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfarmacia`.`Empleado` (
  `idEmpleado` INT NOT NULL AUTO_INCREMENT,
  `idPersona` INT NOT NULL,
  `idTipoEmpleado` INT NOT NULL,
  `idSucursal` INT NULL,
  `usuario` VARCHAR(45) NULL,
  `contrasenia` VARCHAR(45) NULL,
  `direccionImagen` VARCHAR(10000) NULL,
  `fechaRegistro` DATE NOT NULL,
  `estadoEmpleado` VARCHAR(1) NULL,
  PRIMARY KEY (`idEmpleado`),
  CONSTRAINT `fk_Empleado_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `dbfarmacia`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_TipoEmpleado1`
    FOREIGN KEY (`idTipoEmpleado`)
    REFERENCES `dbfarmacia`.`TipoEmpleado` (`idTipoEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_Sucursal1`
    FOREIGN KEY (`idSucursal`)
    REFERENCES `dbfarmacia`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfarmacia`.`TipoTarjeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfarmacia`.`TipoTarjeta` (
  `idTipoTarjeta` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `fechaEmision` DATE NOT NULL,
  `fechaVencimiento` DATE NULL,
  `estadoTipoTarjeta` VARCHAR(1) NULL,
  PRIMARY KEY (`idTipoTarjeta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfarmacia`.`TarjetaAcumulacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfarmacia`.`TarjetaAcumulacion` (
  `idTarjetaAcumulacion` INT NOT NULL AUTO_INCREMENT,
  `fechaEmision` DATE NOT NULL,
  `fechaVencimiento` DATE NULL,
  `idTipoTarjeta` INT NOT NULL,
  `idCliente` INT NOT NULL,
  `estadoTarjetaAcumulacion` VARCHAR(1) NULL,
  PRIMARY KEY (`idTarjetaAcumulacion`),
  CONSTRAINT `fk_TarjetaAcumulacion_TipoTarjeta1`
    FOREIGN KEY (`idTipoTarjeta`)
    REFERENCES `dbfarmacia`.`TipoTarjeta` (`idTipoTarjeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TarjetaAcumulacion_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `dbfarmacia`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfarmacia`.`TipoMovimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfarmacia`.`TipoMovimiento` (
  `idTipoMovimiento` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoMovimiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfarmacia`.`Impuesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfarmacia`.`Impuesto` (
  `idImpuesto` INT NOT NULL AUTO_INCREMENT,
  `impuesto` FLOAT NOT NULL COMMENT 'Porcentaje del impuesto establecido.',
  `fechaVigencia` DATE NOT NULL,
  `fechaExpiracion` DATE NULL,
  PRIMARY KEY (`idImpuesto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfarmacia`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfarmacia`.`Factura` (
  `idFactura` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `hora` TIME NULL,
  `subTotal` FLOAT NULL,
  `descuento` FLOAT NULL,
  `impuesto` FLOAT NULL,
  `Total` FLOAT NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  `idCliente` INT NULL,
  `idImpuesto` INT NOT NULL,
  `RTN` VARCHAR(45) NULL,
  `idEmpleado` INT NOT NULL,
  `estadoFactura` VARCHAR(1) NULL,
  PRIMARY KEY (`idFactura`),
  CONSTRAINT `fk_Factura_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `dbfarmacia`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Impuesto1`
    FOREIGN KEY (`idImpuesto`)
    REFERENCES `dbfarmacia`.`Impuesto` (`idImpuesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Empleado1`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `dbfarmacia`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfarmacia`.`Movimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfarmacia`.`Movimientos` (
  `idMovimientos` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `Hora` TIME NULL,
  `cantidadPuntos` INT NULL,
  `idTarjetaAcumulacion` INT NOT NULL,
  `idTipoMovimiento` INT NOT NULL,
  `idFactura` INT NOT NULL,
  `estadoMovimiento` VARCHAR(1) NULL,
  PRIMARY KEY (`idMovimientos`),
  CONSTRAINT `fk_Movimientos_TarjetaAcumulacion1`
    FOREIGN KEY (`idTarjetaAcumulacion`)
    REFERENCES `dbfarmacia`.`TarjetaAcumulacion` (`idTarjetaAcumulacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movimientos_TipoMovimiento1`
    FOREIGN KEY (`idTipoMovimiento`)
    REFERENCES `dbfarmacia`.`TipoMovimiento` (`idTipoMovimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movimientos_Factura1`
    FOREIGN KEY (`idFactura`)
    REFERENCES `dbfarmacia`.`Factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfarmacia`.`TipoDescuento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfarmacia`.`TipoDescuento` (
  `idTipoDescuento` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoDescuento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfarmacia`.`Descuento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfarmacia`.`Descuento` (
  `idDescuento` INT NOT NULL AUTO_INCREMENT,
  `descuento` FLOAT NOT NULL COMMENT 'Porcentaje del descuento que se va a dar.',
  `idTipoDescuento` INT NOT NULL,
  `fechaEmision` DATE NULL,
  `fechaExpiro` DATE NULL,
  PRIMARY KEY (`idDescuento`),
  CONSTRAINT `fk_Descuento_TipoDescuento1`
    FOREIGN KEY (`idTipoDescuento`)
    REFERENCES `dbfarmacia`.`TipoDescuento` (`idTipoDescuento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfarmacia`.`FormaPago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfarmacia`.`FormaPago` (
  `idFormaPago` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idFormaPago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfarmacia`.`Factura_X_FormaPago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfarmacia`.`Factura_X_FormaPago` (
  `idFactura` INT NOT NULL,
  `idFormaPago` INT NOT NULL,
  `cantidadPago` FLOAT NULL,
  PRIMARY KEY (`idFactura`, `idFormaPago`),
  CONSTRAINT `fk_Factura_has_FormaPago_Factura1`
    FOREIGN KEY (`idFactura`)
    REFERENCES `dbfarmacia`.`Factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_has_FormaPago_FormaPago1`
    FOREIGN KEY (`idFormaPago`)
    REFERENCES `dbfarmacia`.`FormaPago` (`idFormaPago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfarmacia`.`Descuento_X_Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfarmacia`.`Descuento_X_Factura` (
  `idDescuento` INT NOT NULL,
  `idFactura` INT NOT NULL,
  PRIMARY KEY (`idDescuento`, `idFactura`),
  CONSTRAINT `fk_Descuento_has_Factura_Descuento1`
    FOREIGN KEY (`idDescuento`)
    REFERENCES `dbfarmacia`.`Descuento` (`idDescuento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Descuento_has_Factura_Factura1`
    FOREIGN KEY (`idFactura`)
    REFERENCES `dbfarmacia`.`Factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfarmacia`.`Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfarmacia`.`Inventario` (
  `idInventario` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `idSucursal` INT NOT NULL,
  `estadoInventario` VARCHAR(1) NULL,
  PRIMARY KEY (`idInventario`),
  CONSTRAINT `fk_Inventario_Sucursal1`
    FOREIGN KEY (`idSucursal`)
    REFERENCES `dbfarmacia`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfarmacia`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfarmacia`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nombreProducto` VARCHAR(45) NOT NULL,
  `fechaElaboracion` DATE NOT NULL,
  `fechaVencimiento` DATE NULL,
  `serie` VARCHAR(45) NULL,
  `direccionImagen` VARCHAR(10000) NULL,
  `idInventario` INT NOT NULL,
  `fechaRegistro` DATE NOT NULL,
  `estadoProducto` VARCHAR(1) NULL,
  PRIMARY KEY (`idProducto`),
  CONSTRAINT `fk_Producto_Inventario1`
    FOREIGN KEY (`idInventario`)
    REFERENCES `dbfarmacia`.`Inventario` (`idInventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfarmacia`.`PresentacionProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfarmacia`.`PresentacionProducto` (
  `idPresentacionProducto` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPresentacionProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfarmacia`.`Factura_X_Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfarmacia`.`Factura_X_Producto` (
  `idFactura` INT NOT NULL,
  `idProducto` INT NOT NULL,
  `idPresentacionProducto` INT NOT NULL,
  `Precio` DOUBLE NULL,
  PRIMARY KEY (`idFactura`, `idProducto`),
  CONSTRAINT `fk_Factura_has_Producto_Factura1`
    FOREIGN KEY (`idFactura`)
    REFERENCES `dbfarmacia`.`Factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_has_Producto_Producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `dbfarmacia`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_X_Producto_PresentacionProducto1`
    FOREIGN KEY (`idPresentacionProducto`)
    REFERENCES `dbfarmacia`.`PresentacionProducto` (`idPresentacionProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfarmacia`.`ProductosVarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfarmacia`.`ProductosVarios` (
  `idProductosVarios` INT NOT NULL,
  `idProducto` INT NOT NULL,
  PRIMARY KEY (`idProductosVarios`),
  CONSTRAINT `fk_ProductosVarios_Producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `dbfarmacia`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfarmacia`.`Medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfarmacia`.`Medicamento` (
  `idMedicamento` INT NOT NULL AUTO_INCREMENT,
  `indicacion` VARCHAR(10000) NULL,
  `elaboracion` VARCHAR(10000) NULL COMMENT 'Campo para describir con que materiales/quimicos fue hecho el producto.',
  `idProducto` INT NOT NULL,
  PRIMARY KEY (`idMedicamento`),
  CONSTRAINT `fk_Medicamento_Producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `dbfarmacia`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfarmacia`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfarmacia`.`Proveedor` (
  `idProveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `RTN` VARCHAR(45) NOT NULL,
  `fechaRegistro` DATE NOT NULL,
  `direccion` VARCHAR(1000) NOT NULL,
  `Correo` VARCHAR(100) NOT NULL,
  `estadoProveedor` VARCHAR(1) NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfarmacia`.`SalidaProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfarmacia`.`SalidaProducto` (
  `idSalidaProducto` INT NOT NULL AUTO_INCREMENT,
  `fechaHora` DATETIME NOT NULL,
  `observacion` VARCHAR(3000) NULL,
  `idSucursalLlegada` INT NOT NULL,
  PRIMARY KEY (`idSalidaProducto`),
  CONSTRAINT `fk_Salida_Sucursal1`
    FOREIGN KEY (`idSucursalLlegada`)
    REFERENCES `dbfarmacia`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfarmacia`.`Medicamento_X_Salida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfarmacia`.`Medicamento_X_Salida` (
  `idMedicamento` INT NOT NULL,
  `idSalida` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`idMedicamento`, `idSalida`),
  CONSTRAINT `fk_Medicamento_has_Salida_Medicamento1`
    FOREIGN KEY (`idMedicamento`)
    REFERENCES `dbfarmacia`.`Medicamento` (`idMedicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medicamento_has_Salida_Salida1`
    FOREIGN KEY (`idSalida`)
    REFERENCES `dbfarmacia`.`SalidaProducto` (`idSalidaProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfarmacia`.`cubiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfarmacia`.`cubiculo` (
  `idcubiculo` INT NOT NULL AUTO_INCREMENT,
  `nombreCubiculo` VARCHAR(45) NULL,
  `estadoCubiculo` VARCHAR(1) NULL,
  PRIMARY KEY (`idcubiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfarmacia`.`Producto_X_cubiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfarmacia`.`Producto_X_cubiculo` (
  `idProducto` INT NOT NULL,
  `idcubiculo` INT NOT NULL,
  PRIMARY KEY (`idProducto`, `idcubiculo`),
  CONSTRAINT `fk_Producto_has_cubiculo_Producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `dbfarmacia`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_cubiculo_cubiculo1`
    FOREIGN KEY (`idcubiculo`)
    REFERENCES `dbfarmacia`.`cubiculo` (`idcubiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfarmacia`.`Estante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfarmacia`.`Estante` (
  `idEstante` INT NOT NULL AUTO_INCREMENT,
  `numeroEstante` VARCHAR(45) NOT NULL,
  `idcubiculo` INT NOT NULL,
  `idSucursal` INT NOT NULL,
  `estadoEstanto` VARCHAR(1) NULL,
  PRIMARY KEY (`idEstante`),
  CONSTRAINT `fk_Estante_cubiculo1`
    FOREIGN KEY (`idcubiculo`)
    REFERENCES `dbfarmacia`.`cubiculo` (`idcubiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estante_Sucursal1`
    FOREIGN KEY (`idSucursal`)
    REFERENCES `dbfarmacia`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfarmacia`.`TelefonoProveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfarmacia`.`TelefonoProveedor` (
  `idTelefonoProveedor` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NOT NULL,
  `Compania` VARCHAR(45) NULL,
  `idProveedor` INT NOT NULL,
  PRIMARY KEY (`idTelefonoProveedor`),
  CONSTRAINT `fk_TelefonoProveedor_Proveedor1`
    FOREIGN KEY (`idProveedor`)
    REFERENCES `dbfarmacia`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfarmacia`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfarmacia`.`Compra` (
  `idCompra` INT NOT NULL AUTO_INCREMENT,
  `idProducto` INT NOT NULL,
  `idProveedor` INT NOT NULL,
  `PrecioCosto` FLOAT NULL,
  `FechaCompra` VARCHAR(45) NULL,
  `Lote` VARCHAR(45) NULL,
  `estadoCompra` VARCHAR(1) NULL,
  `idPresentacionProducto` INT NOT NULL,
  PRIMARY KEY (`idCompra`),
  CONSTRAINT `fk_Compra_Producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `dbfarmacia`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra_Proveedor1`
    FOREIGN KEY (`idProveedor`)
    REFERENCES `dbfarmacia`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra_PresentacionProducto1`
    FOREIGN KEY (`idPresentacionProducto`)
    REFERENCES `dbfarmacia`.`PresentacionProducto` (`idPresentacionProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfarmacia`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfarmacia`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `idEmpleado` INT NOT NULL,
  `fechaPedido` DATE NOT NULL,
  `estadoPedido` VARCHAR(1) NULL,
  PRIMARY KEY (`idPedido`),
  CONSTRAINT `fk_Pedido_Empleado1`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `dbfarmacia`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfarmacia`.`Producto_X_Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfarmacia`.`Producto_X_Pedido` (
  `idPedido` INT NOT NULL,
  `idProducto` INT NOT NULL,
  `idPresentacionProducto` INT NOT NULL,
  `idProveedor` INT NOT NULL,
  PRIMARY KEY (`idPedido`, `idProducto`, `idPresentacionProducto`),
  CONSTRAINT `fk_Producto_has_Pedido_Producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `dbfarmacia`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_Pedido_Pedido1`
    FOREIGN KEY (`idPedido`)
    REFERENCES `dbfarmacia`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_X_Pedido_PresentacionProducto1`
    FOREIGN KEY (`idPresentacionProducto`)
    REFERENCES `dbfarmacia`.`PresentacionProducto` (`idPresentacionProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_X_Pedido_Proveedor1`
    FOREIGN KEY (`idProveedor`)
    REFERENCES `dbfarmacia`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfarmacia`.`Precio_X_Presentacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfarmacia`.`Precio_X_Presentacion` (
  `idPrecioPresentacion` INT NOT NULL AUTO_INCREMENT,
  `idProducto` INT NOT NULL,
  `idPresentacionProducto` INT NOT NULL,
  `precioVenta` FLOAT NULL,
  `Cantidad` INT NULL,
  `fechaVigencia` DATE NOT NULL,
  `fechaFin` DATE NULL,
  PRIMARY KEY (`idPrecioPresentacion`),
  CONSTRAINT `fk_Precio_X_Presentacion_Producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `dbfarmacia`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Precio_X_Presentacion_PresentacionProducto1`
    FOREIGN KEY (`idPresentacionProducto`)
    REFERENCES `dbfarmacia`.`PresentacionProducto` (`idPresentacionProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
