-- MySQL Script generated by MySQL Workbench
-- Tue Jul  2 22:12:48 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_farmacia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `CondicionEspecial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CondicionEspecial` (
  `idCondicionEspecial` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCondicionEspecial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `pnombre` VARCHAR(45) NOT NULL,
  `snombre` VARCHAR(45) NULL,
  `papellido` VARCHAR(45) NOT NULL,
  `sapellido` VARCHAR(45) NULL,
  `identidad` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `genero` VARCHAR(45) NULL,
  `direccion` VARCHAR(200) NULL,
  `idCondicionEspecial` INT NOT NULL,
  PRIMARY KEY (`idPersona`),
  CONSTRAINT `fk_Persona_CondicionEspecial1`
    FOREIGN KEY (`idCondicionEspecial`)
    REFERENCES `CondicionEspecial` (`idCondicionEspecial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Telefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Telefono` (
  `idTelefono` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NOT NULL,
  `tipoTelefono` VARCHAR(45) NULL COMMENT 'El numero de telefono puede ser:\n-Empresarial: Tigo o Claro\n-Casa\n-Trabajo\n-Personal',
  `idPersona` INT NOT NULL,
  PRIMARY KEY (`idTelefono`),
  CONSTRAINT `fk_Telefono_Persona`
    FOREIGN KEY (`idPersona`)
    REFERENCES `Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TipoCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TipoCliente` (
  `idTipoCliente` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL COMMENT '-Normal\n-especial\n-etc...',
  PRIMARY KEY (`idTipoCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `fechaRegistro` DATE NOT NULL,
  `idPersona` INT NOT NULL,
  `idTipoCliente` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  CONSTRAINT `fk_Cliente_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_TipoCliente1`
    FOREIGN KEY (`idTipoCliente`)
    REFERENCES `TipoCliente` (`idTipoCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TipoEmpleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TipoEmpleado` (
  `idTipoEmpleado` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL COMMENT '-Gerente\n-Farmaceutico\n-Conserje\n-etc...',
  PRIMARY KEY (`idTipoEmpleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sucursal` (
  `idSucursal` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(1000) NOT NULL,
  `telefono` VARCHAR(100) NULL,
  PRIMARY KEY (`idSucursal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Empleado` (
  `idEmpleado` INT NOT NULL AUTO_INCREMENT,
  `fechaRegistro` DATE NOT NULL,
  `idPersona` INT NOT NULL,
  `idTipoEmpleado` INT NOT NULL,
  `idSucursal` INT NULL,
  `usuario` VARCHAR(45) NULL,
  `contrasenia` VARCHAR(45) NULL,
  `direccionImagen` VARCHAR(10000) NULL,
  `Empleadocol` VARCHAR(45) NULL,
  PRIMARY KEY (`idEmpleado`),
  CONSTRAINT `fk_Empleado_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_TipoEmpleado1`
    FOREIGN KEY (`idTipoEmpleado`)
    REFERENCES `TipoEmpleado` (`idTipoEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_Sucursal1`
    FOREIGN KEY (`idSucursal`)
    REFERENCES `Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TipoTarjeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TipoTarjeta` (
  `idTipoTarjeta` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `fechaEmision` DATE NOT NULL,
  `fechaVencimiento` DATE NULL,
  PRIMARY KEY (`idTipoTarjeta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TarjetaAcumulacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TarjetaAcumulacion` (
  `idTarjetaAcumulacion` INT NOT NULL AUTO_INCREMENT,
  `fechaEmision` DATE NULL,
  `fechaVencimiento` DATE NULL,
  `idTipoTarjeta` INT NOT NULL,
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`idTarjetaAcumulacion`),
  CONSTRAINT `fk_TarjetaAcumulacion_TipoTarjeta1`
    FOREIGN KEY (`idTipoTarjeta`)
    REFERENCES `TipoTarjeta` (`idTipoTarjeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TarjetaAcumulacion_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TipoMovimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TipoMovimiento` (
  `idTipoMovimiento` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoMovimiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Impuesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Impuesto` (
  `idImpuesto` INT NOT NULL AUTO_INCREMENT,
  `impuesto` FLOAT NOT NULL COMMENT 'Porcentaje del impuesto establecido.',
  `fechaVigencia` DATE NULL,
  `fechaExpiracion` DATE NULL,
  PRIMARY KEY (`idImpuesto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Factura` (
  `idFactura` INT NOT NULL AUTO_INCREMENT,
  `fechaHora` DATETIME NOT NULL,
  `subTotal` FLOAT NULL,
  `descuento` FLOAT NULL,
  `impuesto` FLOAT NULL,
  `Total` FLOAT NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  `idCliente` INT NULL,
  `idImpuesto` INT NOT NULL,
  `RTN` VARCHAR(45) NULL,
  `idEmpleado` INT NOT NULL,
  PRIMARY KEY (`idFactura`),
  CONSTRAINT `fk_Factura_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Impuesto1`
    FOREIGN KEY (`idImpuesto`)
    REFERENCES `Impuesto` (`idImpuesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Empleado1`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Movimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Movimientos` (
  `idMovimientos` INT NOT NULL AUTO_INCREMENT,
  `fechaHora` DATETIME NULL,
  `cantidadPuntos` INT NULL,
  `idTarjetaAcumulacion` INT NOT NULL,
  `idTipoMovimiento` INT NOT NULL,
  `idEmpleado` INT NOT NULL,
  `idFactura` INT NOT NULL,
  PRIMARY KEY (`idMovimientos`),
  CONSTRAINT `fk_Movimientos_TarjetaAcumulacion1`
    FOREIGN KEY (`idTarjetaAcumulacion`)
    REFERENCES `TarjetaAcumulacion` (`idTarjetaAcumulacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movimientos_TipoMovimiento1`
    FOREIGN KEY (`idTipoMovimiento`)
    REFERENCES `TipoMovimiento` (`idTipoMovimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movimientos_Empleado1`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movimientos_Factura1`
    FOREIGN KEY (`idFactura`)
    REFERENCES `Factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TipoDescuento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TipoDescuento` (
  `idTipoDescuento` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoDescuento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Descuento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Descuento` (
  `idDescuento` INT NOT NULL AUTO_INCREMENT,
  `descuento` FLOAT NOT NULL COMMENT 'Porcentaje del descuento que se va a dar.',
  `idTipoDescuento` INT NOT NULL,
  `fechaEmision` DATE NULL,
  `fechaExpiro` DATE NULL,
  PRIMARY KEY (`idDescuento`),
  CONSTRAINT `fk_Descuento_TipoDescuento1`
    FOREIGN KEY (`idTipoDescuento`)
    REFERENCES `TipoDescuento` (`idTipoDescuento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FormaPago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FormaPago` (
  `idFormaPago` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idFormaPago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Factura_has_FormaPago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Factura_has_FormaPago` (
  `idFactura` INT NOT NULL,
  `idFormaPago` INT NOT NULL,
  `cantidadPago` FLOAT NULL,
  PRIMARY KEY (`idFactura`, `idFormaPago`),
  CONSTRAINT `fk_Factura_has_FormaPago_Factura1`
    FOREIGN KEY (`idFactura`)
    REFERENCES `Factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_has_FormaPago_FormaPago1`
    FOREIGN KEY (`idFormaPago`)
    REFERENCES `FormaPago` (`idFormaPago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Descuento_has_Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Descuento_has_Factura` (
  `idDescuento` INT NOT NULL,
  `idFactura` INT NOT NULL,
  PRIMARY KEY (`idDescuento`, `idFactura`),
  CONSTRAINT `fk_Descuento_has_Factura_Descuento1`
    FOREIGN KEY (`idDescuento`)
    REFERENCES `Descuento` (`idDescuento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Descuento_has_Factura_Factura1`
    FOREIGN KEY (`idFactura`)
    REFERENCES `Factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inventario` (
  `idInventario` INT NOT NULL AUTO_INCREMENT,
  `idSucursal` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idInventario`),
  CONSTRAINT `fk_Inventario_Sucursal1`
    FOREIGN KEY (`idSucursal`)
    REFERENCES `Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nombreProducto` VARCHAR(45) NOT NULL,
  `fechaElaboracion` DATE NOT NULL,
  `fechaVencimiento` DATE NOT NULL,
  `serie` VARCHAR(45) NULL,
  `lote` VARCHAR(45) NULL,
  `precioVenta` FLOAT NOT NULL,
  `precioCosto` FLOAT NOT NULL,
  `direccionImagen` VARCHAR(10000) NULL,
  `idInventario` INT NOT NULL,
  `fechaRegistro` DATE NULL,
  PRIMARY KEY (`idProducto`),
  CONSTRAINT `fk_Producto_Inventario1`
    FOREIGN KEY (`idInventario`)
    REFERENCES `Inventario` (`idInventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Factura_has_Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Factura_has_Producto` (
  `Factura_idFactura` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  `cantidadCaja` INT NULL,
  `cantidadBlister` INT NULL,
  `cantidadUnidad` INT NULL,
  PRIMARY KEY (`Factura_idFactura`, `Producto_idProducto`),
  CONSTRAINT `fk_Factura_has_Producto_Factura1`
    FOREIGN KEY (`Factura_idFactura`)
    REFERENCES `Factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_has_Producto_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProductosVarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProductosVarios` (
  `idProductosVarios` INT NOT NULL,
  `idProducto` INT NOT NULL,
  PRIMARY KEY (`idProductosVarios`),
  CONSTRAINT `fk_ProductosVarios_Producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Medicamento` (
  `idMedicamento` INT NOT NULL AUTO_INCREMENT,
  `indicacion` VARCHAR(1000) NULL,
  `elaboracion` VARCHAR(1000) NULL COMMENT 'Campo para describir con que materiales/quimicos fue hecho el producto.',
  `idProducto` INT NOT NULL,
  PRIMARY KEY (`idMedicamento`),
  CONSTRAINT `fk_Medicamento_Producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proveedor` (
  `idProveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `RTN` VARCHAR(45) NULL,
  `fechaRegistro` DATE NULL,
  `direccion` VARCHAR(1000) NULL,
  `telefono` VARCHAR(100) NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proveedor_has_Medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proveedor_has_Medicamento` (
  `Proveedor_idProveedor` INT NOT NULL,
  `Medicamento_idMedicamento` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `fechaIngreso` DATE NULL,
  PRIMARY KEY (`Proveedor_idProveedor`, `Medicamento_idMedicamento`),
  CONSTRAINT `fk_Proveedor_has_Medicamento_Proveedor1`
    FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proveedor_has_Medicamento_Medicamento1`
    FOREIGN KEY (`Medicamento_idMedicamento`)
    REFERENCES `Medicamento` (`idMedicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Salida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Salida` (
  `idSalida` INT NOT NULL,
  `fechaHora` DATETIME NOT NULL,
  `observacion` VARCHAR(3000) NULL,
  `idSucursalLlegada` INT NOT NULL,
  PRIMARY KEY (`idSalida`),
  CONSTRAINT `fk_Salida_Sucursal1`
    FOREIGN KEY (`idSucursalLlegada`)
    REFERENCES `Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Medicamento_has_Salida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Medicamento_has_Salida` (
  `idMedicamento` INT NOT NULL,
  `idSalida` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`idMedicamento`, `idSalida`),
  CONSTRAINT `fk_Medicamento_has_Salida_Medicamento1`
    FOREIGN KEY (`idMedicamento`)
    REFERENCES `Medicamento` (`idMedicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medicamento_has_Salida_Salida1`
    FOREIGN KEY (`idSalida`)
    REFERENCES `Salida` (`idSalida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cubiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cubiculo` (
  `idcubiculo` INT NOT NULL,
  `nombreCubiculo` VARCHAR(45) NULL,
  PRIMARY KEY (`idcubiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Producto_has_cubiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Producto_has_cubiculo` (
  `Producto_idProducto` INT NOT NULL,
  `cubiculo_idcubiculo` INT NOT NULL,
  PRIMARY KEY (`Producto_idProducto`, `cubiculo_idcubiculo`),
  CONSTRAINT `fk_Producto_has_cubiculo_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_cubiculo_cubiculo1`
    FOREIGN KEY (`cubiculo_idcubiculo`)
    REFERENCES `cubiculo` (`idcubiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Estante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Estante` (
  `idEstante` INT NOT NULL AUTO_INCREMENT,
  `numeroEstante` VARCHAR(45) NULL,
  `cubiculo_idcubiculo` INT NOT NULL,
  `Sucursal_idSucursal` INT NOT NULL,
  PRIMARY KEY (`idEstante`),
  CONSTRAINT `fk_Estante_cubiculo1`
    FOREIGN KEY (`cubiculo_idcubiculo`)
    REFERENCES `cubiculo` (`idcubiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estante_Sucursal1`
    FOREIGN KEY (`Sucursal_idSucursal`)
    REFERENCES `Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cantidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cantidad` (
  `idCantidad` INT NOT NULL AUTO_INCREMENT,
  `cantidadCaja` INT NULL,
  `precioVentaCaja` FLOAT NULL,
  `cantidadBlister` INT NULL,
  `precioVentaBlister` FLOAT NULL,
  `cantidadUnidad` INT NULL,
  `precioVentaUnidad` FLOAT NULL,
  `idProducto` INT NOT NULL,
  PRIMARY KEY (`idCantidad`),
  CONSTRAINT `fk_Cantidad_Producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CantidadEntrante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CantidadEntrante` (
  `idCantidad` INT NOT NULL AUTO_INCREMENT,
  `cantidadCaja` INT NULL,
  `precioCostoCaja` FLOAT NULL,
  `cantidaBlister` INT NULL,
  `precioCostoBlister` FLOAT NULL,
  `cantidadUnidad` INT NULL,
  `precioCostoUnidad` FLOAT NULL,
  `idProveedor` INT NOT NULL,
  `idMedicamento` INT NOT NULL,
  PRIMARY KEY (`idCantidad`),
  CONSTRAINT `fk_CantidadEntrante_Proveedor_has_Medicamento1`
    FOREIGN KEY (`idProveedor` , `idMedicamento`)
    REFERENCES `Proveedor_has_Medicamento` (`Proveedor_idProveedor` , `Medicamento_idMedicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Producto_has_Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Producto_has_Categoria` (
  `Producto_idProducto` INT NOT NULL,
  `Categoria_idCategoria` INT NOT NULL,
  PRIMARY KEY (`Producto_idProducto`, `Categoria_idCategoria`),
  CONSTRAINT `fk_Producto_has_Categoria_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_Categoria_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
